CPUS = {
    1: {
        "brand": "AMD",
        "name": "Ryzen 5 5600X",
        "price": 162.66,
        "core_count": 6,
        "performance_core_clock": 3.7,
        "performance_boost_clock": 4.6,
        "integrated_graphics": None,
    },
    2: {
        "brand": "AMD",
        "name": "Ryzen 7 5800X",
        "price": 217.99,
        "core_count": 8,
        "performance_core_clock": 3.8,
        "performance_boost_clock": 4.7,
        "integrated_graphics": None,
    },
    3: {
        "brand": "Intel",
        "name": "Core i7 13700K",
        "price": 409.00,
        "core_count": 16,
        "performance_core_clock": 3.4,
        "performance_boost_clock": 5.4,
        "integrated_graphics": "Intel UHD Graphics 770",
    },
    4: {
        "brand": "AMD",
        "name": "Ryzen 7 7800X3D",
        "price": 439.00,
        "core_count": 8,
        "performance_core_clock": 4.2,
        "performance_boost_clock": 5.0,
        "integrated_graphics": "Radeon",
    },
    5: {
        "brand": "Intel",
        "name": "Core i9 13900K",
        "price": 569.99,
        "core_count": 24,
        "performance_core_clock": 3.0,
        "performance_boost_clock": 5.8,
        "integrated_graphics": "Intel UHD Graphics 770",
    },
}

CPU_COOLERS = {
    1: {
        "brand": "Cooler Master",
        "name": "Hyper 212 Black Edition",
        "price": 24.99,
        "fan_rpm": "800-2000 RPM",
        "noise_level": "6.5-26 dB",
    },
    2: {
        "brand": "Cooler Master",
        "name": "MASTERLIQUID ML240L RGB V2",
        "price": 96.99,
        "fan_rpm": "650-1800 RPM",
        "noise_level": "6-27 dB",
    },
    3: {
        "brand": "be quiet!",
        "name": "Dark Rock Pro 4",
        "price": 89.90,
        "fan_rpm": "1500 RPM",
        "noise_level": "12.8-24.3 dB",
    },
    4: {
        "brand": "Noctua",
        "name": "NH-D15 chromax.black",
        "price": 89.99,
        "fan_rpm": "300-1500 RPM",
        "noise_level": "19.2-24.6 dB",
    },
    5: {
        "brand": "Thermalright",
        "name": "Peerless Assassin 120 SE",
        "price": 36.90,
        "fan_rpm": "1550 RPM",
        "noise_level": "25.6 dB",
    },
}

MOTHERBOARDS = {
    1: {
        "brand": "MSI",
        "name": "MAG B550 TOMAHAWK",
        "price": 169.99,
        "socket": "AM4",
        "form_factor": "ATX",
        "ram_slots": 4,
        "max_ram": 128,
    },
    2: {
        "brand": "MSI",
        "name": "B550-A PRO",
        "price": 139.99,
        "socket": "AM4",
        "form_factor": "ATX",
        "ram_slots": 4,
        "max_ram": 128,
    },
    3: {
        "brand": "MSI",
        "name": "B550M PRO-VDH WIFI",
        "price": 119.99,
        "socket": "AM4",
        "form_factor": "Micro ATX",
        "ram_slots": 4,
        "max_ram": 128,
    },
    4: {
        "brand": "Gigabyte",
        "name": "Z790 AORUS ELITE AX",
        "price": 249.99,
        "socket": "LGA1700",
        "form_factor": "ATX",
        "ram_slots": 4,
        "max_ram": 128,
    },
    5: {
        "brand": "Asus",
        "name": "Prime B450M-A II",
        "price": 79.98,
        "socket": "AM4",
        "form_factor": "Micro ATX",
        "ram_slots": 4,
        "max_ram": 128,
    },
}

MEMORYS_RAM = {
    1: {
        "brand": "Corsair",
        "name": "Vengeance LPX 16GB",
        "price": 37.99,
        "ram_type": "DDR4",
        "ram_speed": 3200,
        "ram_modules": "2 x 8GB",
    },
    2: {
        "brand": "Corsair",
        "name": "Vengeance RGB PRO 32GB",
        "price": 104.98,
        "ram_type": "DDR4",
        "ram_speed": 3600,
        "ram_modules": "2 x 16GB",
    },
    3: {
        "brand": "Corsair",
        "name": "Vengeance LPX 32GB",
        "price": 67.99,
        "ram_type": "DDR4",
        "ram_speed": 3600,
        "ram_modules": "2 x 16GB",
    },
    4: {
        "brand": "G.Skill",
        "name": "Trident Z5 RGB 32GB",
        "price": 104.99,
        "ram_type": "DDR5",
        "ram_speed": 6000,
        "ram_modules": "2 x 32GB",
    },
    5: {
        "brand": "Silicon Power",
        "name": "Gaming 16GB",
        "price": 29.97,
        "ram_type": "DDR4",
        "ram_speed": 3200,
        "ram_modules": "2 x 8GB",
    },
}


STORAGES = {
    1: {
        "brand": "Samsung",
        "name": "980 Pro",
        "price": 119.99,
        "storage_type": "SSD",
        "storage_capacity": 2048,
        "storage_cache": 2048,
        "storage_form_factor": "M.2-2280",
        "storage_interface": "M.2 PCIe 4.0 X4",
    },
    2: {
        "brand": "Samsung",
        "name": "970 Evo Plus",
        "price": 49.99,
        "storage_type": "SSD",
        "storage_capacity": 1024,
        "storage_cache": 1024,
        "storage_form_factor": "M.2-2280",
        "storage_interface": "M.2 PCIe 3.0 X4",
    },
    3: {
        "brand": "Samsung",
        "name": "980 Pro",
        "price": 69.99,
        "storage_type": "SSD",
        "storage_capacity": 1024,
        "storage_cache": 1024,
        "storage_form_factor": "M.2-2280",
        "storage_interface": "M.2 PCIe 4.0 X4",
    },
    4: {
        "brand": "Seagate",
        "name": "Barracuda Compute",
        "price": 55,
        "storage_type": "HDD 7200 RPM",
        "storage_capacity": 2048,
        "storage_cache": 256,
        "storage_form_factor": '3.5"',
        "storage_interface": "SATA 6.0 Gb/s",
    },
    5: {
        "brand": "Western Digital",
        "name": "Caviar Blue",
        "price": 39.45,
        "storage_type": "HDD 7200 RPM",
        "storage_capacity": 1024,
        "storage_cache": 64,
        "storage_form_factor": '3.5"',
        "storage_interface": "SATA 6.0 Gb/s",
    },
}


VIDEO_CARDS = {
    1: {
        "brand": "MSI",
        "name": "GeForce RTX 3060 Ventus 2X 12G",
        "price": 289.99,
        "video_chipset": "GeForce RTX 3060",
        "video_memory": 12,
        "vdeo_core_clock": 1320,
        "video_boost_clock": 1777,
    },
    2: {
        "brand": "Gigabyte",
        "name": "WINDFORCE OC",
        "price": 599.99,
        "video_chipset": "GeForce RTX 4070",
        "video_memory": 12,
        "vdeo_core_clock": 1920,
        "video_boost_clock": 2490,
    },
    3: {
        "brand": "Asus",
        "name": "ROG STRIX GAMING OC",
        "price": 1951.79,
        "video_chipset": "GeForce RTX 4090",
        "video_memory": 24,
        "vdeo_core_clock": 2235,
        "video_boost_clock": 2640,
    },
    4: {
        "brand": "XFX",
        "name": "Speedster MERC 319 CORE",
        "price": 529.99,
        "video_chipset": "Radeon RX 6800 XT",
        "video_memory": 16,
        "vdeo_core_clock": 1825,
        "video_boost_clock": 2250,
    },
    5: {
        "brand": "Sapphire",
        "name": "PULSE",
        "price": 394.76,
        "video_chipset": "Radeon RX 6700 XT",
        "video_memory": 12,
        "vdeo_core_clock": 2321,
        "video_boost_clock": 2581,
    },
}

CASES = {
    1: {
        "brand": "Corsair",
        "name": "4000D Airflow",
        "price": 89.99,
        "case_type": "ATX Mid Tower",
        "Case_color": "Black",
    },
    2: {
        "brand": "NZXT",
        "name": "H5 Flow",
        "price": 94.99,
        "case_type": "ATX Mid Tower",
        "Case_color": "Black",
    },
    3: {
        "brand": "Deepcool",
        "name": "CC560",
        "price": 67.98,
        "case_type": "ATX Mid Tower",
        "Case_color": "Black",
    },
    4: {
        "brand": "Lian Li",
        "name": "O11 Dynamic EVO",
        "price": 152.99,
        "case_type": "ATX Mid Tower",
        "Case_color": "White",
    },
    5: {
        "brand": "Thermaltake",
        "name": "Versa H18",
        "price": 49.99,
        "case_type": "MicroATX Mini Tower",
        "Case_color": "Black",
    },
}

POWER_SUPLYS = {
    1: {
        "brand": "Corsair",
        "name": "RM750e (2023)",
        "price": 99.99,
        "power_suply_type": "ATX",
        "wattage": 750,
        "modular": "Full",
    },
    2: {
        "brand": "Corsair",
        "name": "RM850e (2021)",
        "price": 129.99,
        "power_suply_type": "ATX",
        "wattage": 850,
        "modular": "Full",
    },
    3: {
        "brand": "Thermaltake",
        "name": "Toughpower GX2",
        "price": 67.98,
        "power_suply_type": "ATX",
        "wattage": 600,
        "modular": "No",
    },
    4: {
        "brand": "Gigabyte",
        "name": "UD750GM",
        "price": 84.99,
        "power_suply_type": "ATX",
        "wattage": 750,
        "modular": "Full",
    },
    5: {
        "brand": "Cooler Master",
        "name": "V850 SFX GOLD",
        "price": 135.99,
        "power_suply_type": "ATX",
        "wattage": 850,
        "modular": "Full",
    },
}

OPERATING_SYSTEMS = {
    1: {
        "brand": "Microsoft",
        "name": "Windows 11 Home",
        "price": 117.98,
        "mode": "64-bit",
        "max_supported_memory": 128,
    },
    2: {
        "brand": "Microsoft",
        "name": "Windows 11 Pro",
        "price": 144.99,
        "mode": "64-bit",
        "max_supported_memory": 2048,
    },
    3: {
        "brand": "Microsoft",
        "name": "Windows 10 Pro",
        "price": 129.55,
        "mode": "64-bit",
        "max_supported_memory": 2048,
    },
    4: {
        "brand": "Microsoft",
        "name": "Windows 10 Pro",
        "price": 199.99,
        "mode": "32/64-bit",
        "max_supported_memory": 2048,
    },
    1: {
        "brand": "Microsoft",
        "name": "Windows 8.1 Pro DE",
        "price": 188.07,
        "mode": "64-bit",
        "max_supported_memory": 512,
    },
}

MONITORS = {
    1: {
        "brand": "Asus",
        "name": "TUF Gaming VG27AQ",
        "price": 300.00,
        "screen_size": '27.0"',
        "resolution": "2560x1440",
        "refresh_rate": 165,
        "response_time": 1.0,
        "panel_type": "IPS",
        "aspect_ratio": "16:9",
    },
    2: {
        "brand": "Asus",
        "name": "VG248QG",
        "price": 188.99,
        "screen_size": '24.0"',
        "resolution": "1920x1080",
        "refresh_rate": 165,
        "response_time": 0.5,
        "panel_type": "TN",
        "aspect_ratio": "16:9",
    },
    3: {
        "brand": "Dell",
        "name": "UP3218K",
        "price": 3999.00,
        "screen_size": '32.0"',
        "resolution": "7680x4320",
        "refresh_rate": 60,
        "response_time": 6.0,
        "panel_type": "IPS",
        "aspect_ratio": "16:9",
    },
    4: {
        "brand": "Samsung",
        "name": "Odyssey G9 Neo 549AG952N",
        "price": 1504.28,
        "screen_size": '49.0"',
        "resolution": "5120x1440",
        "refresh_rate": 240,
        "response_time": 1.0,
        "panel_type": "VA",
        "aspect_ratio": "32:9",
    },
    5: {
        "brand": "Alienware",
        "name": "AW3423DWF",
        "price": 999.99,
        "screen_size": '34.2"',
        "resolution": "3440x1440",
        "refresh_rate": 165,
        "response_time": 0.1,
        "panel_type": "QD-OLED",
        "aspect_ratio": "21:9",
    },
}
